- name: Define a configuracao do Puppet Agent
  #when: ansible_os_family == "Debian"
  template:
    src: puppet.conf.j2
    dest: /etc/puppetlabs/puppet/puppet.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart Puppet Agent
  tags: puppetagent
- name: "Allow Puppet ports"
  when: ansible_os_family == "RedHat"
  firewalld:
   port: 8139-8140/tcp
   permanent: yes
   state: enabled
   immediate: yes
  tags: puppetagent
