---
- name: Instala Puppet Agent no Debian 9
  when: ansible_os_family == "Debian"
  apt:
   name: puppet-agent
   state: present
  notify:
    - Start Puppet Agent
  tags: puppetagent
- name: Instala Puppet Agent no RedHat/CentOS 7
  when: ansible_os_family == "RedHat"
  yum:
   name: puppet-agent
   state: present
  notify:
    - Start Puppet Agent
  tags: puppetagent
