---
# handlers file for puppet-agent
- name: Start Puppet Agent
  systemd: 
    name: puppet
    state: started
    enabled: yes
- name: Restart Puppet Agent
  systemd: 
    name: puppet
    state: restarted